name: ctpaga
description: ctpaga.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.14+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cached_network_image: ^2.2.0+1
  camera: ^0.5.8+11
  contacts_service: ^0.4.6
  cupertino_icons: ^0.1.3
  flutter_cache_manager: ^1.2.0
  flutter_emoji: ^2.2.1+1
  flutter_localizations:
    sdk: flutter
  flutter_masked_text: ^0.8.0
  http: ^0.12.2
  image_picker: ^0.6.7+12
  image_cropper: ^1.3.1
  numeric_keyboard: ^1.0.0
  searchable_dropdown: ^1.1.3
  shared_preferences: ^0.5.7+3
  package_info: ^0.4.3
  path_provider: ^1.6.22
  permission_handler: ^5.0.0
  provider: ^4.3.2+2
  pusher_websocket_flutter: ^0.2.0
  share: ^0.6.5+4
  sqflite: ^1.1.6
  toast: ^0.1.5
  url_launcher: ^5.5.2
  video_player: ^0.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter:
  uses-material-design: true

  #import assets
  assets:
    - assets/logo/
    - assets/icons/
    - assets/banks/
    - assets/banks/Venezuela/
    - assets/banks/Panama/
    - assets/banks/USA/
    - assets/videos/botonUSD.mp4
    - assets/videos/botonBs.mp4

flutter_icons:
  image_path: 'assets/logo/logoctpaga.png'
  android: true
  ios: true


