name: ctpaga
description: ctpaga.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  shared_preferences: ^0.5.7+3
  flutter_masked_text: ^0.7.0
  numeric_keyboard: ^1.0.0
  cupertino_icons: ^0.1.3
  http: ^0.12.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  #import assets
  assets:
    - assets/logo/
    - assets/icons/


