
import 'package:ctpaga/views/depositsPage.dart';
import 'package:ctpaga/views/loginPage.dart';
import 'package:ctpaga/views/productsPage.dart';
import 'package:ctpaga/views/perfilPage.dart';

import 'package:flutter/material.dart';

//TODO: Url Api (LocalHost)
String url = "192.168.1.103:8000";
String urlApi = "http://$url/api/auth/";

Color colorGreen = Color.fromRGBO(0,204,96,1);
Color colorGrey = Color.fromRGBO(230,230,230,1);


List listMenu = [
  {
    "title": "Perfil",
    "icon": "assets/icons/perfilMenu.png",
    "page": PerfilPage(),
  },
  {
    "title": "Depósitos",
    "icon": "assets/icons/depositos.png",
    "page": DepositsPage(),
  },
  {
    "title": "Productos",
    "icon": "assets/icons/productos.png",
    "page": ProductsPage(false),
  },
  {
    "title": "Envios",
    "icon": "assets/icons/envios.png",
    "page": ProductsPage(false),
  },
  {
    "title": "Códigos de descuento",
    "icon": "assets/icons/descuento.png",
    "page": ProductsPage(false),
  },
  {
    "title": "Reporte de ventas",
    "icon": "assets/icons/reporte.png",
    "page": ProductsPage(false),
  },
  {
    "title": "Crear otro comercio",
    "icon": "assets/icons/crearComercio.png",
    "page": ProductsPage(false),
  },
  {
    "title": "Recomentar a un comercio",
    "icon": "assets/icons/recomendarComercio.png",
    "page": ProductsPage(false),
  },
  {
    "title": "Pedir ayuda",
    "icon": "assets/icons/ayuda.png",
    "page": ProductsPage(false),
  },
  {
    "title": "Cerrar sesión",
    "icon": "",
    "page": LoginPage(),
  },
];

var listBankUSA = [
  "Alex. Brown & Sons",
  "American Express",
  "Apple Bank for Savings",
  "Bank of America",
  "Bank One Corporation",
  "BankBoston",
  "BB&T",
  "BBVA",
  "Bessemer Trust",
  "Brooklyn Savings Bank",
  "Chase Manhattan Bank",
  "Chemical Bank",
  "Citibank",
  "Citigroup",
  "Dime Savings Bank of New York",
  "Dime Savings Bank of Williamsburgh",
  "Drexel Burnham Lambert",
  "First Boston",
  "Goldman Sachs",
  "Greenwich Savings Bank",
  "JP Morgan Chase",
  "Lehman Brothers",
  "Merrill Lynch",
  "Moore Capital Management",
  "Morgan Stanley",
  "New York Savings Bank",
  "Primer Banco de los Estados Unidos",
  "Riggs Bank",
  "Salomon Brothers",
  "Santander Bank",
  "State Street Corporation",
  "SunTrust Banks",
  "Wachovia",
  "Washington Mutual",
  "Wells Fargo"
  "White Weld & Co.",
];

var listBankPanama = [
  "Allbank Corp",
  "BAC International Bank, Inc.",
  "Balboa Bank & Trust Corp",
  "Banco Aliado S.A.",
  "Banco Azteca (Panamá), S.A.",
  "Banco BAC de Panamá, S.A.",
  "Banco Bolivariano (Panamá), S.A.",
  "Banco Citibank (Panamá,) S.A.",
  "Banco Davivienda (Panamá) S.A.",
  "Banco de Bogotá, S.A.",
  "Banco del Pacífico (Panamá), S.A.",
  "Banco Delta, S.A.",
  "Banco Ficohsa (Panamá), S.A.",
  "Banco G&T Continental (Panamá) S.A. (BMF)",
  "Banco HIPOTECARIO NACIONAL",
  "Banco General, S.A.",
  "Banco Internacional de Costa Rica, S.A (BICSA)",
  "Banco La Hipotecaria, S.A.",
  "Banco Lafise Panamá S.A.",
  "Banco Latinoamericano de Comercio Exterior, S.A. (BLADEX)",
  "Banco Nacional de Panamá",
  "Banco Panamá, S.A",
  "Banco Panameño de la Vivienda, S.A. (BANVIVIENDA)",
  "Banco Pichincha Panamá, S.A.",
  "Banco Prival, S.A. (Español) o Prival Bank, S.A. (en inglés)",
  "Banco Universal, S.A.",
  "Bancolombia S.A.",
  "Banesco S.A.",
  "BANISI, S.A.",
  "Banistmo S.A.",
  "Bank Leumi-Le Israel B.M.",
  "Bank of China Limited",
  "BBP Bank S.A.",
  "BCT Bank International S.A.",
  "Caja de Ahorros",
  "Capital Bank Inc.",
  "Citibank, N.A. Sucursal Panamá",
  "Credicorp Bank S.A.",
  "FPB Bank Inc.",
  "Global Bank Corporation",
  "Korea Exchange Bank, Ltd.",
  "Mega International Commercial Bank Co. Ltd.",
  "Mercantil Bank (Panamá), S.A.",
  "Metrobank, S.A.",
  "MiBanco, S.A.BMF",
  "MMG Bank Corporation",
  "Multibank Inc.",
  "Produbank (Panamá) S.A.",
  "St. Georges Bank & Company, Inc.",
  "The Bank of Nova Scotia (Panamá), S.A.",
  "The Bank of Nova Scotia (SCOTIABANK)",
  "Towerbank International Inc.",
  "Unibank, S.A.",
];

var listBankBs = [
 "100% BANCO",
 "ABN AMRO BANK",
 "BANCAMIGA BANCO MICROFINANCIERO, C.A.",
 "BANCO ACTIVO BANCO COMERCIAL, C.A.",
 "BANCO AGRICOLA",
 "BANCO BICENTENARIO",
 "BANCO CARONI, C.A. BANCO UNIVERSAL",
 "BANCO DE DESARROLLO DEL MICROEMPRESARIO",
 "BANCO DE VENEZUELA S.A.I.C.A.",
 "BANCO DEL CARIBE C.A.",
 "BANCO DEL PUEBLO SOBERANO C.A.",
 "BANCO DEL TESORO",
 "BANCO ESPIRITO SANTO, S.A.",
 "BANCO EXTERIOR C.A.",
 "BANCO INDUSTRIAL DE VENEZUELA",
 "BANCO INTERNACIONAL DE DESARROLLO, C.A.",
 "BANCO MERCANTIL C.A.",
 "BANCO NACIONAL DE CRÉDITO",
 "BANCO OCCIDENTAL DE DESCUENTO",
 "BANCO PLAZA",
 "BANCO PROVINCIAL BBVA",
 "BANCO VENEZOLANO DE CRÉDITO S.A.",
 "BANCRECER S.A. BANCO DE DESARROLLO",
 "BANESCO BANCO UNIVERSAL"  ,
 "BANFANB",
 "BANGENTE",
 "BANPLUS BANCO COMERCIAL C.A",
 "CITIBANK",
 "CORP BANCA",
 "DELSUR BANCO UNIVERSAL",
 "FONDO COMUN",
 "INSTITUTO MUNICIPAL DE CRÉDITO POPULAR",
 "MIBANCO BANCO DE DESARROLLO, C.A.",
 "SOFITASA",
];